src/objects/Patient__c.object
<CustomObject>
    <fields>
        <fullName>Full_Name__c</fullName>
        <label>Full Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Steps_Completed__c</fullName>
        <label>Steps Completed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Patient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DashboardController.cls
public class DashboardController {
    @AuraEnabled
    public static List<Patient__c> getPatients() {
    	return [
            SELECT Full_Name__c
                 , Gender__c
            	 , Steps_Completed__c
            	 , Goal__c
                 , Height__c
       	      FROM Patient__c 
          ORDER BY createdDate ASC
        ];
    } 
    
	@AuraEnabled
    public static Patient__c findPatientById(String patientId) {
    	return [ 
            SELECT Full_Name__c
            	 , Gender__c
            	 , Height__c
       	      FROM Patient__c 
             WHERE Id = :patientId];
    }
}